- name: catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: setup node JS repo file
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed 

  - name: check roboshop user exists or not 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: create user roboshop
    when: output.rc != 0 # if the expression is true then only the module will run
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue artifact
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: coping catalogue.service to  /etc/systemd/system/catalogue.service 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload, enable and start catalogue service
    ansible.builtin.systemd:
      daemon_reload: true
       
  - name: coping mongo.repo to /etc/yum.repos.d/mongo.repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading schema
    ansible.builtin.command: "mongo --host mongodb.sureshdevops.online < /app/schema/catalogue.js"

  - name: restart catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: true