- name: dispatch component
  hosts: dispatch
  become: yes
  tasks:
  - name: installing go lang
    ansible.builtin.yum:
      name: golang 
      state: installed

  - name: check roboshop user exists or not 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: create user roboshop
    when: output.rc != 0 # if the expression is true then only the module will run
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download dispatch artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp

  - name: extract dispatch artifact
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes

  - name: check  
    ansible.builtin.command: "go mod init dispatch"
    register: output
    ignore_errors: true
  
  - name: install
    when: output.rc != 0 # if the expression is true then only the module will run
    ansible.builtin.command: "go mod init dispatch"
    ignore_errors: true
    args:
      chdir: /app
    
  - name: check  
    ansible.builtin.command: "go get"
    register: output1
    ignore_errors: true
  
  - name: install
    when: output1.rc != 0 # if the expression is true then only the module will run
    ansible.builtin.command: "go get"
    ignore_errors: true
    args:
      chdir: /app

  - name: check  
    ansible.builtin.command: "go build"
    register: output2
    ignore_errors: true
  
  - name: install
    when: output2.rc != 0 # if the expression is true then only the module will run
    ansible.builtin.command: "go build"
    ignore_errors: true
    args:
      chdir: /app

  - name: coping payment.service to  /etc/systemd/system/dispatch.service 
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service

  - name: daemon reload, enable and start dispatch service
    ansible.builtin.systemd:
      daemon_reload: true

  - name: restart dispatch
    ansible.builtin.service:
      name: dispatch
      state: restarted
      enabled: true