- name: mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: disabling mysql default version
    ansible.builtin.command: yum module disable mysql -y 

  - name: coping mysql repo
    ansible.builtin.copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: installing mysql community service
    ansible.builtin.yum:
      name: mysql-community-server
      state: installed

  - name: enable and start mysqld service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: changing mysql default password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1

  - name: connecting to mysql service
    ansible.builtin.command: mysql -uroot -pRoboShop@1