- name: payment component
  hosts: payment
  become: yes
  tasks:
  - name: installing 
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - "python36" 
    - "gcc" 
    - "python3-devel"

  - name: check roboshop user exists or not 
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  
  - name: create user roboshop
    when: output.rc != 0 # if the expression is true then only the module will run
    become: yes
    ansible.builtin.user:
      name: roboshop

  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download payment artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/payment.zip
      dest: /tmp

  - name: extract payment artifact
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: pip3.6 install -r requirements.txt
    args:
      chdir: /app

  - name: coping payment.service to  /etc/systemd/system/payment.service 
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload, enable and start payment service
    ansible.builtin.systemd:
      daemon_reload: true

  - name: restart payment
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: true