- name: payment component
  hosts: payment
  become: yes
  tasks:
  - name: installing 
    ansible.builtin.yum:
      name: {{item}}
      state: installed
    loop:
    - python36 
    - gcc 
    - python3-devel

  - name: 