- name: rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configuring repos
    ansible.builtin.shell: {{item}}
    loop:
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: installing rabbitmq-server
    ansible.builtin.yum: 
      name: rabbitmq-server
      state: installed

  - name: enabling and starting rabbitmq service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create rabbitmq user
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions to the rabbitmq user
    ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"